#! /bin/sh
#
# Stop on error
set -e

echo " -> Building"

bindir="${PWD}/bin"

GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o "${bindir}/hesabucli-mac" hesabu.go
GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o "${bindir}/hesabucli" hesabu.go

echo " -> New mac build at: ./bin/hesabucli-mac"
echo " -> New build at: ./bin/hesabucli"

./bin/hesabucli test/array.json
echo '{"a": "1 + 2 + b", "b": "7"}' | ./bin/hesabucli