#! /bin/sh
#
# Stop on error and output every command before executing it
set -e

[ -z "$DEBUG" ] || set -x

cd "$(dirname "$0")/.."

script/bootstrap
script/build

echo " -> Testing"
go test ./... -coverprofile=coverage.out
